  name: Build Server for Deployment

  on:
    push:
      branches:
      - master
    workflow_dispatch:
      inputs:
          used-branch:
            description: Branch to build from
            default: master
            required: true
  jobs:
    ubuntu-build:
      name: Build Server files
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: Build with Gradle
          uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
          with:
            arguments: build
            gradle-version: current
            build-root-directory: ./backend
        - name: Save Backend files
          uses: actions/upload-artifact@v3
          with:
            name: backend-build
            path: backend/build/libs/
        - run:  cd ./frontend
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
            cache-dependency-path: frontend/package-lock.json
        - run: npm ci
        - run: npm run build --if-present
        - name: Save Frontend files
          uses: actions/upload-artifact@v3
          with:
            name: frontend-build
            path: frontend/coverage/crd/
